from flask import Flask
from pymongo import MongoClient

app = Flask(__name__)

AUTHMASTER_OWNER          = "WILL BE OVERWRITTEN BY COMMAND LINE ARGUMENTS"
MONGODB_CONNECTION_STRING = "WILL BE OVERWRITTEN BY COMMAND LINE ARGUMENTS"
MONGODB_DATABASE_NAME     = "WILL BE OVERWRITTEN BY COMMAND LINE ARGUMENTS"
MONGODB_COLLECTION_NAME   = "WILL BE OVERWRITTEN BY COMMAND LINE ARGUMENTS"
GOOGLE_USERINFO_ENDPOINT  = "https://www.googleapis.com/oauth2/v2/userinfo"